[tox]
envlist = compliance,integration-tests




[testenv:compliance]
skip_install = True
deps =
    black==24.3.0
    flake8
stoponfail = True
commands =
    black --check redisbench_admin
    flake8 redisbench_admin

[testenv:format]
skip_install = True
deps =
    black==24.3.0
commands =
    black redisbench_admin

[testenv:integration-tests]
deps =
    -r{toxinidir}/dev_requirements.txt
    pytest-cov
    tox-docker
docker =
    rts_datasink
    db_server
    client_server

passenv = TST_BUILDER_X,TST_RUNNER_X,GH_TOKEN,TST_REDIS_DIR,DOCKER_HOST,DOCKER_TLS_VERIFY,DOCKER_CERT_PATH,TST_BINARY_REDIS_DIR


stoponfail = True
commands =
    coverage erase
    pytest --cov=redisbench_admin --cov-report=term-missing -ra {posargs}
    coverage xml

[docker]
docker_host = unix:///var/run/docker.sock

docker =
    rts_datasink
    db_server
    client_server


[docker:rts_datasink]
image = redis/redis-stack-server:7.4.0-v0
# Expose ports to the testenv
expose =
    RTS_PORT=6379/tcp

healthcheck_cmd = redis-cli ping
healthcheck_interval = 1
healthcheck_timeout = 3
healthcheck_retries = 30

[docker:db_server]
image = ghcr.io/linuxserver/openssh-server
ports =
    2222:2222/tcp
environment =
    PUBLIC_KEY_DIR=/test-ssh
    PUBLIC_KEY=tox_rsa.pub
    USER_NAME=ubuntu
volumes =
    bind:ro:{toxinidir}/tests/test_data/test-ssh/pub:/test-ssh

[docker:client_server]
image = ghcr.io/linuxserver/openssh-server
ports =
    222:2222/tcp
environment =
    PUBLIC_KEY_DIR=/test-ssh
    PUBLIC_KEY=tox_rsa.pub
    USER_NAME=ubuntu
volumes =
    bind:ro:{toxinidir}/tests/test_data/test-ssh/pub:/test-ssh
